/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#082f49",
        "surface-tint": "#0b6b8a",
        "on-secondary-fixed": "#231a11",
        "on-secondary-fixed-variant": "#51453a",
        "on-tertiary-container": "#e56b3f",
        "on-surface": "#1a1c1f",
        "tertiary-container": "#7c2d12",
        "on-tertiary-fixed": "#431407",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#f3a17f",
        "surface-variant": "#e2e2e7",
        "error": "#ba1a1a",
        "primary-container": "#043b5c",
        "outline": "#737780",
        "on-background": "#1a1c1f",
        "surface-container-highest": "#e2e2e7",
        "secondary-fixed-dim": "#d5c3b5",
        "primary": "#064e78",
        "primary-fixed": "#dff3fb",
        "inverse-on-surface": "#f1f0f5",
        "surface-container-high": "#e8e8ed",
        "on-secondary-container": "#706256",
        "surface-dim": "#dad9de",
        "on-primary-container": "#dff3fb",
        "on-error": "#ffffff",
        "tertiary": "#6f2f1e",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#075e83",
        "secondary-fixed": "#f2dfd0",
        "tertiary-fixed-dim": "#c95335",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#7c2d12",
        "surface": "#f9f9fe",
        "secondary-container": "#f2dfd0",
        "outline-variant": "#c3c6d1",
        "surface-container": "#eeedf2",
        "secondary": "#695c50",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "background": "#f9f9fe",
        "surface-bright": "#f9f9fe",
        "on-surface-variant": "#43474f",
        "inverse-surface": "#2f3034",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f4f3f8",
        "inverse-primary": "#7dd3e8",
        "primary-fixed-dim": "#a9dceb",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        gutter: "24px",
        "section-padding": "120px",
        base: "8px",
      },
      fontFamily: {
        "headline-lg": ["Nexa Bold", "Nexa", "Arial", "sans-serif"],
        "body-md": ["Nexa Bold", "Nexa", "Arial", "sans-serif"],
        "headline-lg-mobile": ["Nexa Bold", "Nexa", "Arial", "sans-serif"],
        "display-lg": ["Nexa Bold", "Nexa", "Arial", "sans-serif"],
        "headline-md": ["Nexa Bold", "Nexa", "Arial", "sans-serif"],
        "label-sm": ["Nexa Bold", "Nexa", "Arial", "sans-serif"],
        "body-lg": ["Nexa Bold", "Nexa", "Arial", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["48px", { lineHeight: "56px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "display-lg": [
          "64px",
          { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "500" }],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
