/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    regions: Region;
    countries: Country;
    stays: Stay;
    trips: Trip;
    faqs: Faq;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    regions: RegionsSelect<false> | RegionsSelect<true>;
    countries: CountriesSelect<false> | CountriesSelect<true>;
    stays: StaysSelect<false> | StaysSelect<true>;
    trips: TripsSelect<false> | TripsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'trips-page': TripsPage;
    'socials-page': SocialsPage;
    'faq-page': FaqPage;
    'contact-page': ContactPage;
    'about-page': AboutPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'trips-page': TripsPageSelect<false> | TripsPageSelect<true>;
    'socials-page': SocialsPageSelect<false> | SocialsPageSelect<true>;
    'faq-page': FaqPageSelect<false> | FaqPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions".
 */
export interface Region {
  id: number;
  name: string;
  /**
   * Use lowercase kebab-case. Example: red-sea
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries".
 */
export interface Country {
  id: number;
  name: string;
  /**
   * Use lowercase kebab-case. Example: indonesia
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stays".
 */
export interface Stay {
  id: number;
  name: string;
  /**
   * Use lowercase kebab-case. Example: buddy-dive-resort
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trips".
 */
export interface Trip {
  id: number;
  title: string;
  /**
   * Use lowercase kebab-case. Example: magic-of-the-maldives
   */
  slug: string;
  /**
   * Optional old UnderseaX URL to redirect, such as /gay-scuba-trips/havana.html or the full old URL.
   */
  legacyUrl?: string | null;
  region: number | Region;
  countries: (number | Country)[];
  stays: (number | Stay)[];
  /**
   * Place a clickable destination pin on the homepage map for this trip.
   */
  mapPin: {
    showOnHomepage?: boolean | null;
    /**
     * 0 is the far left of the map and 100 is the far right.
     */
    xPercent?: number | null;
    /**
     * 0 is the top of the map and 100 is the bottom.
     */
    yPercent?: number | null;
    color:
      | 'amber'
      | 'apricot'
      | 'aqua'
      | 'berry'
      | 'blush'
      | 'brick'
      | 'bronze'
      | 'coral'
      | 'crimson'
      | 'deep-blue'
      | 'emerald'
      | 'forest'
      | 'gold'
      | 'hot-pink'
      | 'indigo'
      | 'lavender'
      | 'lemon'
      | 'mint'
      | 'ocean'
      | 'orchid'
      | 'peacock'
      | 'plum'
      | 'seafoam'
      | 'terracotta';
  };
  tripStyle: 'liveaboard' | 'land-resort';
  gender: 'male' | 'female' | 'mixed';
  /**
   * Used in the trip URL, for example /2027/maldives.
   */
  tripYear?: number | null;
  tripStart: string;
  tripEnd: string;
  isNew?: boolean | null;
  /**
   * Include this trip in the homepage Featured Trips carousel.
   */
  featuredOnHomepage?: boolean | null;
  days: number;
  nights: number;
  /**
   * Short formatted intro shown near the top of the trip page.
   */
  summary: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Displayed inside the main trip information panel.
   */
  coverImage: number | Media;
  /**
   * Optional image shown in the top page banner. Falls back to the main image.
   */
  bannerImage?: (number | null) | Media;
  contentSections?: {
    /**
     * Main formatted description for the trip detail page.
     */
    overview?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Formatted package inclusions shown on the trip detail page.
     */
    packageIncludes?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Formatted exclusions shown on the trip detail page.
     */
    notIncluded?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    flights?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    deposit?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  pricingOptions?:
    | {
        label: string;
        amount: number;
        note?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Add Instagram or Facebook post URLs to show embedded social posts on the trip page.
   */
  socialEmbeds?:
    | {
        platform: 'instagram' | 'facebook';
        title?: string | null;
        /**
         * Paste the full Instagram or Facebook post URL. The frontend converts it into an embed automatically.
         */
        postUrl: string;
        id?: string | null;
      }[]
    | null;
  bookingLabel: string;
  bookingHref: string;
  /**
   * Optional trip-specific image for the insurance panel. Falls back to the site-wide default image.
   */
  insuranceImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  category?: string | null;
  sortOrder?: number | null;
  answer: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'regions';
        value: number | Region;
      } | null)
    | ({
        relationTo: 'countries';
        value: number | Country;
      } | null)
    | ({
        relationTo: 'stays';
        value: number | Stay;
      } | null)
    | ({
        relationTo: 'trips';
        value: number | Trip;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions_select".
 */
export interface RegionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries_select".
 */
export interface CountriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stays_select".
 */
export interface StaysSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trips_select".
 */
export interface TripsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  legacyUrl?: T;
  region?: T;
  countries?: T;
  stays?: T;
  mapPin?:
    | T
    | {
        showOnHomepage?: T;
        xPercent?: T;
        yPercent?: T;
        color?: T;
      };
  tripStyle?: T;
  gender?: T;
  tripYear?: T;
  tripStart?: T;
  tripEnd?: T;
  isNew?: T;
  featuredOnHomepage?: T;
  days?: T;
  nights?: T;
  summary?: T;
  coverImage?: T;
  bannerImage?: T;
  contentSections?:
    | T
    | {
        overview?: T;
        packageIncludes?: T;
        notIncluded?: T;
        flights?: T;
        deposit?: T;
      };
  pricingOptions?:
    | T
    | {
        label?: T;
        amount?: T;
        note?: T;
        id?: T;
      };
  socialEmbeds?:
    | T
    | {
        platform?: T;
        title?: T;
        postUrl?: T;
        id?: T;
      };
  bookingLabel?: T;
  bookingHref?: T;
  insuranceImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  category?: T;
  sortOrder?: T;
  answer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyName: string;
  tagline: string;
  footerBlurb: string;
  contact: {
    tollFreePhone: string;
    internationalPhone?: string | null;
    email: string;
    addressLines?:
      | {
          line: string;
          id?: string | null;
        }[]
      | null;
  };
  certifications?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  insurance: {
    logo?: (number | null) | Media;
    defaultImage?: (number | null) | Media;
    buyButtonLabel: string;
    buyButtonHref: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    /**
     * Shown only if no logo overlay image is uploaded.
     */
    title?: string | null;
    description?: string | null;
    logo?: (number | null) | Media;
    image: number | Media;
    primaryCtaLabel: string;
    primaryCtaHref: string;
    secondaryCtaLabel?: string | null;
    secondaryCtaHref?: string | null;
  };
  mapSection: {
    title: string;
    description?: string | null;
    buttonLabel: string;
    buttonHref: string;
  };
  featuredTrips: {
    title: string;
    description?: string | null;
  };
  story: {
    title: string;
    body: {
      paragraph: string;
      id?: string | null;
    }[];
    image: number | Media;
    buttonLabel?: string | null;
    buttonHref?: string | null;
  };
  cta: {
    title: string;
    description: string;
    phoneLabel: string;
    emailLabel: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trips-page".
 */
export interface TripsPage {
  id: number;
  title: string;
  description: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "socials-page".
 */
export interface SocialsPage {
  id: number;
  title?: string | null;
  description?: string | null;
  socialLinks?:
    | {
        eyebrow?: string | null;
        title?: string | null;
        description?: string | null;
        buttonLabel?: string | null;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  latestSocialMoments?: {
    title?: string | null;
    description?: string | null;
    tiles?:
      | {
          eyebrow?: string | null;
          title?: string | null;
          description?: string | null;
          image?: (number | null) | Media;
          buttonLabel?: string | null;
          href?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-page".
 */
export interface FaqPage {
  id: number;
  title: string;
  description: string;
  highlights?:
    | {
        icon: string;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  title: string;
  intro: string;
  image: number | Media;
  imageText: string;
  privacyNote: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  title?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  staffSection?: {
    title?: string | null;
    description?: string | null;
    officeTitle?: string | null;
    officeStaff?:
      | {
          name?: string | null;
          role?: string | null;
          image?: (number | null) | Media;
          bio?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          id?: string | null;
        }[]
      | null;
    tripLeadersTitle?: string | null;
    tripLeaders?:
      | {
          name?: string | null;
          role?: string | null;
          image?: (number | null) | Media;
          bio?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          id?: string | null;
        }[]
      | null;
  };
  pressSection?: {
    title?: string | null;
    description?: string | null;
    items?:
      | {
          title?: string | null;
          ctaLabel?: string | null;
          description?: string | null;
          pdf?: (number | null) | Media;
          externalUrl?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  tagline?: T;
  footerBlurb?: T;
  contact?:
    | T
    | {
        tollFreePhone?: T;
        internationalPhone?: T;
        email?: T;
        addressLines?:
          | T
          | {
              line?: T;
              id?: T;
            };
      };
  certifications?:
    | T
    | {
        label?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  insurance?:
    | T
    | {
        logo?: T;
        defaultImage?: T;
        buyButtonLabel?: T;
        buyButtonHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        description?: T;
        logo?: T;
        image?: T;
        primaryCtaLabel?: T;
        primaryCtaHref?: T;
        secondaryCtaLabel?: T;
        secondaryCtaHref?: T;
      };
  mapSection?:
    | T
    | {
        title?: T;
        description?: T;
        buttonLabel?: T;
        buttonHref?: T;
      };
  featuredTrips?:
    | T
    | {
        title?: T;
        description?: T;
      };
  story?:
    | T
    | {
        title?: T;
        body?:
          | T
          | {
              paragraph?: T;
              id?: T;
            };
        image?: T;
        buttonLabel?: T;
        buttonHref?: T;
      };
  cta?:
    | T
    | {
        title?: T;
        description?: T;
        phoneLabel?: T;
        emailLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trips-page_select".
 */
export interface TripsPageSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "socials-page_select".
 */
export interface SocialsPageSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  socialLinks?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        buttonLabel?: T;
        href?: T;
        id?: T;
      };
  latestSocialMoments?:
    | T
    | {
        title?: T;
        description?: T;
        tiles?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              image?: T;
              buttonLabel?: T;
              href?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-page_select".
 */
export interface FaqPageSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  highlights?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  image?: T;
  imageText?: T;
  privacyNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  staffSection?:
    | T
    | {
        title?: T;
        description?: T;
        officeTitle?: T;
        officeStaff?:
          | T
          | {
              name?: T;
              role?: T;
              image?: T;
              bio?: T;
              id?: T;
            };
        tripLeadersTitle?: T;
        tripLeaders?:
          | T
          | {
              name?: T;
              role?: T;
              image?: T;
              bio?: T;
              id?: T;
            };
      };
  pressSection?:
    | T
    | {
        title?: T;
        description?: T;
        items?:
          | T
          | {
              title?: T;
              ctaLabel?: T;
              description?: T;
              pdf?: T;
              externalUrl?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}