services:
  postgres:
    image: postgres:16
    container_name: undersea-expeditions-payload-postgres
    environment:
      POSTGRES_DB: undersea_payload
      POSTGRES_PASSWORD: undersea_cms_dev_password
      POSTGRES_USER: undersea_cms
    ports:
      - "55632:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
